name = "ewu-helper-license-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ewu_helper_licenses"
database_id = "dd31c855-4d9e-4f9e-94ed-e17483c2c1cc"

[vars]
JWT_EXPIRATION_HOURS = "72"

[[kv_namespaces]]
binding = "ADMIN_KV"
id = "c58fa6cd40084673b0b25c586e3b565f"
